import type { Metadata } from "next";
import "./globals.css";

import ThemeRegistry from "<src>/theme/ThemeRegistry";
import AppLayout from "<src>/ui/AppLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <AppLayout>{children}</AppLayout>
        </body>
      </ThemeRegistry>
    </html>
  );
}
